name: paulogan
favicon: null
layout_spectrum: 1
typography_spectrum: 0.95729
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#747776'
    - '#8f8c8c'
    - '#bdbbbb'
    - '#a8a6a6'
  brandStrength: 0.875
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
