name: paulogan
favicon: null
layout_spectrum: 0.9431930996943265
typography_spectrum: 0.18444246170111
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.40689229499548674
  lightness: 0.16828784346580505
  saturation: 0.9829074735753238
  rhythmicContrast: 0.48538100090809166
purpose: []
